CREATE TABLESPACE micro_user_data
DATAFILE 'D:\Oracle\oradata\ORCL\micro_user_data.dbf' 
SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED 
EXTENT MANAGEMENT LOCAL;

--SELECT NAME, OPEN_MODE, RESTRICTED FROM V$PDBS;
--ALTER PLUGGABLE DATABASE ORCLPDB OPEN;
--ALTER SESSION SET CONTAINER = ORCLPDB;


alter session set "_ORACLE_SCRIPT"=true;

CREATE USER usr_nova
IDENTIFIED BY 1234
DEFAULT TABLESPACE micro_user_data
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE TO usr_nova;
GRANT UNLIMITED TABLESPACE TO usr_nova;

-- Verify tablespace and user
SELECT TABLESPACE_NAME, STATUS FROM DBA_TABLESPACES;
SELECT USERNAME, DEFAULT_TABLESPACE FROM DBA_USERS WHERE USERNAME = 'USR_NOVA';
